<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>

    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <WarningLevel>4</WarningLevel>
    <BaseOutputPath>..\out\out\</BaseOutputPath>

    <AssemblyName>UnicodeRegEx</AssemblyName>
    <AssemblyTitle>UnicodeRegEx</AssemblyTitle>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>

  </PropertyGroup>

  <ItemGroup>
    <Reference Include="UnicodeRegEx.Interop">
      <HintPath>..\out\UnicodeRegEx.Interop.dll</HintPath>
      <EmbedInteropTypes>true</EmbedInteropTypes>
      <Private>false</Private>
    </Reference>
    <ProjectReference Include="..\lib\UnicodeRegExLib.vcxproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReference>
  </ItemGroup>

</Project>
